**Problem 1**

Import Numpy as np

In [1]:

import numpy as np

**Problem 2**

Create a 1D array of numbers from 0 to 9.

In [3]:
np.array([0,1,2,3,4,5,6,7,8,9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Problem 3**

Create a 3×3 numpy array of all True’s.

In [ ]:
array_true=np.full([3,3],True)

In [7]:
array2=np.ones((3,3),dtype=bool)
array2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

**Problem 4**

Extract all odd numbers from arr.

In [8]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
condition=np.mod(arr,2)==1
np.extract(condition,arr)



array([1, 3, 5, 7, 9])

In [27]:
b=arr(arr%2!=0)
b

TypeError: 'numpy.ndarray' object is not callable

**Problem 5**

Replace all odd numbers in arr with -1.

In [15]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2==1]=-1
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

**Problem 6**

Convert a 1D array to a 2D array with 2 rows.

In [18]:
arr1=np.arange(10)
np.reshape(arr1,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Problem 7** 

Stack arrays a and b vertically.

In [24]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

**Problem 8**

Stack the arrays a and b horizontally.

In [25]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

**Problem 9**

Get the common items between a and b.

In [26]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

**Problem 10**

From array a remove all items present in array b

In [34]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
array=np.setdiff1d(a,b)
array

array([1, 2, 3, 4])

**Problem 11**

Get the positions where elements of a and b match

In [38]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.where(a==b))


(array([1, 3, 5, 7], dtype=int64),)


**Problem 12** 

Get all items between 5 and 10 from a.

In [40]:
a = np.array([2,5, 6, 1, 9, 10, 3, 27])
a[2:5]

array([6, 1, 9])

**Problem 13**

Swap columns 1 and 2 in the array arr.

In [53]:
arr = np.arange(9).reshape(3,3)
arr
arr[:,[0,1]]=arr[:,[1,0]]
arr


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

**Problem 14**

Swap rows 1 and 2 in the array arr.

In [60]:
arr = np.arange(9).reshape(3,3)
arr
arr[(0,1),:]=arr[(1,0),:]
arr


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

**Problem 15**

Reverse the rows of a 2D array arr.

In [62]:
arr = np.arange(9).reshape(3,3)
arr2=np.fliplr(arr)
arr2

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

**Problem 16**

Reverse the columns of a 2D array arr.

In [80]:
arr = np.arange(9).reshape(3,3)
#np.flip(arr)
arr=np.flipud(arr)
arr

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

**Problem 17**

Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10

In [73]:
arr=np.random.uniform(0,1,(5,3))
arr

array([[0.17292473, 0.27561893, 0.13335613],
       [0.04959972, 0.24477309, 0.85098591],
       [0.21406227, 0.77496681, 0.14523118],
       [0.58135099, 0.09574047, 0.55975199],
       [0.22305911, 0.03453934, 0.23509318]])

**Problem 18**

Print or show only 3 decimal places of the numpy array rand_arr.

In [75]:
arr=np.random.uniform(0,1,(5,3))
np.around(arr,2)

array([[0.72, 0.03, 0.79],
       [0.38, 0.26, 0.26],
       [0.55, 0.59, 0.1 ],
       [0.99, 0.62, 0.18],
       [0.4 , 0.69, 0.85]])